---
name: Feature Request
description: Use this template to file a feature request.
title: "[Feature]: "
labels: ["enhancement", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Sertha Teeewattana
  - type: dropdown
    id: request-type
    attributes:
      label: Type of request?
      options:
        - New Feature
        - Enhancement
        - Other
  - type: dropdown
    id: os-suggestion
    attributes:
      label: What is the OS which you want to suggest?
      options:
        - Windows
        - Mac
        - Linux
        - Mobile
        - Selections
  - type: textarea
    id: feature-details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what do you want
      placeholder: Feature details!
---
